"""
pdf_export.py — turn an "Ask the AI" answer into a branded, downloadable PDF.

build_answer_pdf(question, answer, scope, meetings_searched, generated_on) -> bytes

The answer comes back from Claude as light markdown (## headings, **bold**, bullet lists).
We convert that into reportlab flowables so the PDF reads like a clean meeting brief, with
an AIOS header band on every page and a footer with page numbers.
"""
import io
import re
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer

ACCENT = colors.HexColor("#1d4ed8")
INK = colors.HexColor("#0f1b3a")
BODY = colors.HexColor("#28324a")
MUTED = colors.HexColor("#6b7a99")

PAGE_W, PAGE_H = A4
MARGIN = 18 * mm
BAND_H = 16 * mm


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("title", parent=base["Normal"], fontName="Helvetica-Bold",
                                fontSize=19, leading=23, textColor=INK, spaceAfter=2),
        "question": ParagraphStyle("question", parent=base["Normal"], fontName="Helvetica-Oblique",
                                   fontSize=11.5, leading=16, textColor=ACCENT, spaceBefore=2, spaceAfter=4),
        "meta": ParagraphStyle("meta", parent=base["Normal"], fontName="Helvetica",
                               fontSize=8.5, leading=12, textColor=MUTED, spaceAfter=2),
        "h1": ParagraphStyle("h1", parent=base["Normal"], fontName="Helvetica-Bold",
                             fontSize=15, leading=19, textColor=INK, spaceBefore=12, spaceAfter=5),
        "h2": ParagraphStyle("h2", parent=base["Normal"], fontName="Helvetica-Bold",
                             fontSize=12.5, leading=16, textColor=ACCENT, spaceBefore=11, spaceAfter=4),
        "h3": ParagraphStyle("h3", parent=base["Normal"], fontName="Helvetica-Bold",
                             fontSize=11, leading=15, textColor=INK, spaceBefore=8, spaceAfter=3),
        "body": ParagraphStyle("body", parent=base["Normal"], fontName="Helvetica",
                               fontSize=10.5, leading=15.5, textColor=BODY, spaceAfter=6),
        "bullet": ParagraphStyle("bullet", parent=base["Normal"], fontName="Helvetica",
                                 fontSize=10.5, leading=15.5, textColor=BODY, leftIndent=16,
                                 bulletIndent=4, spaceAfter=3),
    }


def _inline(text: str) -> str:
    """Escape XML, then re-apply the inline markup reportlab understands (**bold**, `code`)."""
    out = escape(text)
    out = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", out)
    out = re.sub(r"`(.+?)`", r'<font face="Courier">\1</font>', out)
    return out


def _flowables(answer: str, styles: dict) -> list:
    flow = []
    for raw in (answer or "").splitlines():
        line = raw.rstrip()
        stripped = line.strip()

        if not stripped:
            continue
        if re.fullmatch(r"-{3,}|_{3,}|\*{3,}", stripped):           # horizontal rule
            flow.append(Spacer(1, 2))
            flow.append(HRFlowable(width="100%", thickness=0.6, color=colors.HexColor("#d6deec")))
            flow.append(Spacer(1, 4))
            continue

        m = re.match(r"(#{1,6})\s+(.*)", stripped)                  # heading
        if m:
            level = len(m.group(1))
            style = styles["h1"] if level == 1 else styles["h2"] if level == 2 else styles["h3"]
            flow.append(Paragraph(_inline(m.group(2)), style))
            continue

        b = re.match(r"[-*•]\s+(.*)", stripped)                     # bullet
        if b:
            flow.append(Paragraph(_inline(b.group(1)), styles["bullet"], bulletText="•"))
            continue

        n = re.match(r"(\d+)[.)]\s+(.*)", stripped)                 # numbered item
        if n:
            flow.append(Paragraph(_inline(n.group(2)), styles["bullet"], bulletText=f"{n.group(1)}."))
            continue

        flow.append(Paragraph(_inline(stripped), styles["body"]))   # paragraph
    return flow


def _decorate(canvas, doc):
    """Header band + footer drawn on every page."""
    canvas.saveState()
    # header band
    canvas.setFillColor(ACCENT)
    canvas.rect(0, PAGE_H - BAND_H, PAGE_W, BAND_H, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawString(MARGIN, PAGE_H - 10.5 * mm, "AIOS  ·  Meeting Intelligence")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(PAGE_W - MARGIN, PAGE_H - 10.5 * mm, "AI MEETING REVIEW")
    # footer
    canvas.setFillColor(MUTED)
    canvas.setFont("Helvetica", 8)
    canvas.drawString(MARGIN, 12 * mm, "Generated by AIOS · Meeting Intelligence")
    canvas.drawRightString(PAGE_W - MARGIN, 12 * mm, f"Page {doc.page}")
    canvas.restoreState()


def build_answer_pdf(question: str, answer: str, scope: str,
                     meetings_searched: int, generated_on: str) -> bytes:
    """Render one AI answer to a branded PDF and return the bytes."""
    styles = _styles()
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=BAND_H + 10 * mm, bottomMargin=20 * mm,
        leftMargin=MARGIN, rightMargin=MARGIN,
        title="AIOS Meeting Review",
    )

    story = [
        Paragraph("Meeting Review", styles["title"]),
        Paragraph(f"“{escape((question or '').strip())}”", styles["question"]),
        Paragraph(
            f"Scope: {escape(str(scope))} &nbsp;·&nbsp; Searched {meetings_searched} meeting(s) "
            f"&nbsp;·&nbsp; Generated {escape(generated_on)}",
            styles["meta"],
        ),
        Spacer(1, 4),
        HRFlowable(width="100%", thickness=1, color=ACCENT),
        Spacer(1, 8),
    ]
    story.extend(_flowables(answer, styles))

    doc.build(story, onFirstPage=_decorate, onLaterPages=_decorate)
    return buf.getvalue()
